from __future__ import annotations

import gzip
from pathlib import Path

Import("env")

PROJECT_DIR = Path(env["PROJECT_DIR"])
SRC = PROJECT_DIR / "embedded" / "recovery" / "index.html"
OUT_DIR = PROJECT_DIR / "include" / "generated"
OUT = OUT_DIR / "recovery_browser_asset.h"


def write_recovery_asset() -> None:
    raw = SRC.read_bytes()
    gz = gzip.compress(raw, compresslevel=9, mtime=0)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Auto-generated by scripts/embed_assets.py")
    lines.append("static const unsigned char RECOVERY_BROWSER_HTML_GZ[] PROGMEM = {")

    for i in range(0, len(gz), 12):
        chunk = gz[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    lines.append("};")
    lines.append(f"static const size_t RECOVERY_BROWSER_HTML_GZ_LEN = {len(gz)};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="ascii")


write_recovery_asset()
